---
# These settings are synced to GitHub by https://probot.github.io/apps/settings/

_extends: .github:.github/default-settings.yml

repository: 
  name: .github
  private: false

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
